<ol>
    <li>Skalar, 1 Dimensi, [1]</li>
    <li>Vektor / Array, 1+ Dimensi, [1,2] -> 2 Dimensi</li>
    <li>Vektor / Array, 1+ Dimensi, [1,2,3] -> 3 Dimensi</li>
    <li>Matriks, Gabungan Vektor, Terdiri Dari Baris Dan Kolom</li>
    <li>Tensor, Gabungan Matriks</li>
</ol>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
# 0 Dimension
d0 = tf.ones((1))
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [4]:
d1 = tf.ones((2,2))
d1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>