# Opening

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

# Tensorflow Constant

In [ ]:
c0 = tf.constant(1)
c0

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
c1 = tf.constant([1,1])
c1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
c2 = tf.constant([[1,2],[3,4]])
c2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
c3 = tf.constant([
                  [[1,2],[3,4],[5,6]],
                  [[6,5],[4,3],[2,1]]
                  ])
c3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[6, 5],
        [4, 3],
        [2, 1]]], dtype=int32)>

In [ ]:
c4 = tf.constant(2, shape=())
c4

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
c5 = tf.constant(2, shape=(2,))
c5

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
c6 = tf.constant(2, shape=(2,2))
c6

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [ ]:
c7 = tf.constant(2, shape=(2,2,2))
c7

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]], dtype=int32)>

In [ ]:
c8 = tf.constant(2, shape=(2,2,2), dtype=tf.float16)
c8

<tf.Tensor: shape=(2, 2, 2), dtype=float16, numpy=
array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]], dtype=float16)>

In [ ]:
c3[0]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
c3[0][0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
c3[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
c3.shape

TensorShape([2, 3, 2])

In [ ]:
c3.get_shape()

TensorShape([2, 3, 2])

In [ ]:
c3.ndim

3

# Tensorflow Variable

In [ ]:
v0 = tf.Variable(1)
v0

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
v1 = tf.Variable([1,1])
v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
v2 = tf.Variable([[1,2],[3,4]])
v2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
v3 = tf.Variable([
                  [[1,2],[3,4]],
                  [[5,6],[7,8]]
                  ])
v3

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
v3[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
v3[0][0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
v3[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
v3.shape

TensorShape([2, 2, 2])

In [ ]:
v3.get_shape()

TensorShape([2, 2, 2])

In [ ]:
v3.dtype

tf.int32

In [ ]:
try:
  print(v3.size)
except:
  print("Size is not useful")

Size is not useful


In [ ]:
tf.size(v3)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tf.size(v3).numpy()

8

In [ ]:
test = np.arange(1,121)

cons = tf.constant(test,shape=(2,3,4,5))
cons

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [ ]:
cons[:1]

<tf.Tensor: shape=(1, 3, 4, 5), dtype=int64, numpy=
array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]],

        [[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]]])>

In [ ]:
cons[:2, :2]

<tf.Tensor: shape=(2, 2, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])>

In [ ]:
cons[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=int64, numpy=
array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]],


       [[[61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70]],

        [[81, 82, 83, 84, 85],
         [86, 87, 88, 89, 90]]]])>

In [ ]:
cons[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[21, 22],
         [26, 27]]],


       [[[61, 62],
         [66, 67]],

        [[81, 82],
         [86, 87]]]])>

# Tensorflow Constant vs Tensorflow Variable

In [ ]:
t1 = tf.constant(1)
t2 = tf.Variable(1)

In [ ]:
try:
  t1.assign(2)
  print(t1)
except:
  print("Error")

Error


In [ ]:
try:
  t2.assign(2)
  print(t2)
except:
  print("Error")

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


# Random And Shuffle Tensor

In [ ]:
ran1 = tf.random.Generator.from_seed(42)
ran1 = ran1.normal(shape=(2,2))
ran1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
ran2 = tf.random.Generator.from_seed(42)
ran2 = ran2.normal(shape=(2,2))
ran2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
ran1 == ran2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.8003555 , -0.40393865],
       [-0.27906767,  1.0251801 ]], dtype=float32)>

In [ ]:
co1 = tf.constant([[10,2],[30,4],[33,4],[50,5]])
co1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  2],
       [30,  4],
       [33,  4],
       [50,  5]], dtype=int32)>

In [ ]:
co2 = tf.random.shuffle(co1)
co2

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  2],
       [50,  5],
       [33,  4],
       [30,  4]], dtype=int32)>

In [ ]:
co3 = tf.random.shuffle(co1)
co3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[30,  4],
       [33,  4],
       [50,  5],
       [10,  2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
co4 = tf.random.shuffle(co1)
co4

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[50,  5],
       [10,  2],
       [30,  4],
       [33,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
co5 = tf.random.shuffle(co1)
co5

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[50,  5],
       [10,  2],
       [30,  4],
       [33,  4]], dtype=int32)>

# Others

In [ ]:
tf.ones([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([2,2],dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

In [ ]:
import numpy as np
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
tf.constant(a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
tf.constant(a,shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [ ]:
b = np.arange(1,9)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
try:
  tf.constant(b,shape=(2,2))
except:
  print("Unmatched shape of transformation matrices")
  print(2*2,"doesn't equal to",8)

Unmatched shape of transformation matrices
4 doesn't equal to 8


# Tensorflow Arithmethic

n1 cols = n2rows

In [ ]:
import tensorflow as tf

a = tf.constant([[1,2],[3,4]])
a + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
a * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [ ]:
a - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -3],
       [-2, -1]], dtype=int32)>

In [ ]:
b = tf.constant([[1,2],[3,4]])

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [ ]:
tf.subtract(b,a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
c = tf.constant([[1],[2]])
c

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [ ]:
tf.matmul(a,c)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 5],
       [11]], dtype=int32)>

In [ ]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
a.shape

TensorShape([2, 2])

In [ ]:
d = tf.constant([[1],[2]])
d.shape

TensorShape([2, 1])

In [ ]:
a @ d

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 5],
       [11]], dtype=int32)>

In [ ]:
d

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [ ]:
tf.transpose(d)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

<h3>Changing Data Type Tensor</h3>

In [1]:
import tensorflow as tf
be = tf.constant([1],dtype=tf.int16)
be

<tf.Tensor: shape=(1,), dtype=int16, numpy=array([1], dtype=int16)>

In [3]:
be.dtype

tf.int16

In [2]:
af = tf.cast(be,dtype=tf.float16)
af

<tf.Tensor: shape=(1,), dtype=float16, numpy=array([1.], dtype=float16)>

In [4]:
af.dtype

tf.float16

In [5]:
be2 = tf.constant([[1,2],[3,4]], dtype=tf.float16)
be2, be2.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float16)>, tf.float16)

In [7]:
af2 = tf.cast(be2, dtype=tf.int16)
af2, af2.dtype

(<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
 array([[1, 2],
        [3, 4]], dtype=int16)>, tf.int16)

<h3>Aggregation on Tensor</h3>

In [8]:
d = tf.constant([-19,-8])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-19,  -8], dtype=int32)>

In [9]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([19,  8], dtype=int32)>

In [13]:
import numpy as np
ran = tf.constant(np.random.randint(0,100,size=50))
ran

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15, 98,  4, 41,  6, 24, 63, 12, 77, 89, 10, 90, 37,  9, 74, 23, 16,
       64, 34, 52, 35,  5, 37, 29, 94, 16, 58, 60, 58, 35,  1, 33, 20, 24,
       98, 54, 81, 54, 22, 77, 66, 96, 10, 73, 16, 59, 44, 32, 18, 11])>

In [14]:
# Minimum Value
tf.reduce_min(ran)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [15]:
# Maximum Value
tf.reduce_max(ran)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [17]:
# Mean Value
tf.reduce_mean(ran)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [18]:
# Total Value
tf.reduce_sum(ran)

<tf.Tensor: shape=(), dtype=int64, numpy=2154>

In [26]:
ran2 = tf.cast(ran,dtype=tf.float64)
print(tf.math.reduce_std(ran2))
print(round(tf.math.reduce_std(ran2).numpy(),2))

tf.Tensor(28.94742821046457, shape=(), dtype=float64)
28.95


In [27]:
ran2 = tf.cast(ran,dtype=tf.float64)
print(tf.math.reduce_variance(ran2))
print(round(tf.math.reduce_variance(ran2).numpy(),2))

tf.Tensor(837.9536, shape=(), dtype=float64)
837.95
