<ol>
    <li>Skalar, 1 Dimensi, [1]</li>
    <li>Vektor / Array, 1+ Dimensi, [1,2] -> 2 Dimensi</li>
    <li>Vektor / Array, 1+ Dimensi, [1,2,3] -> 3 Dimensi</li>
    <li>Matriks, Gabungan Vektor, Terdiri Dari Baris Dan Kolom</li>
    <li>Tensor, Gabungan Matriks</li>
</ol>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
c0 = tf.constant(1, shape=(1))
c0

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [4]:
c1 = tf.constant(1,shape=(1,2))
c1

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 1]], dtype=int32)>

In [5]:
c2 = tf.constant(2, shape=(2,2))
c2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [6]:
c3 = tf.constant(2, shape=(2,2,2))
c3

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]], dtype=int32)>

In [7]:
v1 = tf.Variable(1)
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [8]:
v2 = tf.Variable([1])
v2

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)>

In [9]:
v3 = tf.Variable([1,2])
v3

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>