<a href="https://colab.research.google.com/github/KurapikaZoldyck/KurapikaZoldyck/blob/main/Tensorflow/Introduction%20to%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<ol>
    <li>Skalar, 1 Dimensi, [1]</li>
    <li>Vektor / Array, 1+ Dimensi, [1,2] -> 2 Dimensi</li>
    <li>Vektor / Array, 1+ Dimensi, [1,2,3] -> 3 Dimensi</li>
    <li>Matriks, Gabungan Vektor, Terdiri Dari Baris Dan Kolom</li>
    <li>Tensor, Gabungan Matriks</li>
</ol>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
cx = tf.constant(7)
cx

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
c0 = tf.constant(1, shape=(1))
c0

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [5]:
c0[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
try:
  c0[0].assign(2)
except:
  print("Can't Change")

Can't Change


In [7]:
c1 = tf.constant(1,shape=(1,2))
c1

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 1]], dtype=int32)>

In [8]:
c2 = tf.constant(2, shape=(2,2))
c2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [9]:
c3 = tf.constant(2, shape=(2,2,2))
c3

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]], dtype=int32)>

In [10]:
c3b = tf.constant(2, shape=(2,2,2),dtype=tf.float16)
c3b

<tf.Tensor: shape=(2, 2, 2), dtype=float16, numpy=
array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]], dtype=float16)>

In [11]:
v1 = tf.Variable(1)
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [12]:
v2 = tf.Variable([1])
v2

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)>

In [13]:
v2[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
v2[0].assign(1)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)>

In [15]:
v3 = tf.Variable([1,2])
v3

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [16]:
v4 = tf.Variable([[1,2],[3,4]])
v4

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [17]:
v5 = tf.Variable([[[1,2],[3,4]],[[5,6],[7,8]]])
v5

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [18]:
v5[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [19]:
v5[0][0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [20]:
v5[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [21]:
v5.dtype

tf.int32

In [22]:
v5.shape

TensorShape([2, 2, 2])

In [26]:
v5.get_shape()

TensorShape([2, 2, 2])

In [24]:
c1.ndim

2

<h3>Random Tensor</h3>

In [1]:
import tensorflow as tf

ran1 = tf.random.Generator.from_seed(42)
ran1 = ran1.normal(shape=(2,2))
ran1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [2]:
ran2 = tf.random.Generator.from_seed(42)
ran2 = ran2.normal(shape=(2,2))
ran2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [3]:
ran1 == ran2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

<h3>Aritmethic Operator</h3>

In [ ]:
import tensorflow as tf

a = tf.Variable([1])
b = tf.Variable([2])

add = tf.add(a,b)
add

In [ ]:
sub = tf.math.subtract(b,a)
sub

In [ ]:
c = tf.Variable([[1,2],[3,4]])
d = tf.Variable([[5,6],[7,8]])

mul = tf.multiply(c,d)
mul

In [ ]:
matmul = tf.matmul(c,d)
matmul