<a href="https://colab.research.google.com/github/KurapikaZoldyck/KurapikaZoldyck/blob/main/Tensorflow/Introduction%20to%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Opening

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

# Tensorflow Constant

In [3]:
c0 = tf.constant(1)
c0

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
c1 = tf.constant([1,1])
c1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [5]:
c2 = tf.constant([[1,2],[3,4]])
c2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
c3 = tf.constant([
                  [[1,2],[3,4],[5,6]],
                  [[6,5],[4,3],[2,1]]
                  ])
c3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[6, 5],
        [4, 3],
        [2, 1]]], dtype=int32)>

In [7]:
c4 = tf.constant(2, shape=())
c4

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
c5 = tf.constant(2, shape=(2,))
c5

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [9]:
c6 = tf.constant(2, shape=(2,2))
c6

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [10]:
c7 = tf.constant(2, shape=(2,2,2))
c7

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]], dtype=int32)>

In [11]:
c8 = tf.constant(2, shape=(2,2,2), dtype=tf.float16)
c8

<tf.Tensor: shape=(2, 2, 2), dtype=float16, numpy=
array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]], dtype=float16)>

In [12]:
c3[0]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [13]:
c3[0][0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [14]:
c3[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
c3.shape

TensorShape([2, 3, 2])

In [16]:
c3.get_shape()

TensorShape([2, 3, 2])

In [17]:
c3.ndim

3

# Tensorflow Variable

In [18]:
v0 = tf.Variable(1)
v0

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [19]:
v1 = tf.Variable([1,1])
v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>

In [20]:
v2 = tf.Variable([[1,2],[3,4]])
v2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [21]:
v3 = tf.Variable([
                  [[1,2],[3,4]],
                  [[5,6],[7,8]]
                  ])
v3

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [22]:
v3[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
v3[0][0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [24]:
v3[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [25]:
v3.shape

TensorShape([2, 2, 2])

In [26]:
v3.get_shape()

TensorShape([2, 2, 2])

In [27]:
v3.dtype

tf.int32

# Tensorflow Constant vs Tensorflow Variable

In [28]:
t1 = tf.constant(1)
t2 = tf.Variable(1)

In [29]:
try:
  t1.assign(2)
  print(t1)
except:
  print("Error")

Error


In [30]:
try:
  t2.assign(2)
  print(t2)
except:
  print("Error")

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


# Random And Shuffle Tensor

In [31]:
ran1 = tf.random.Generator.from_seed(42)
ran1 = ran1.normal(shape=(2,2))
ran1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [32]:
ran2 = tf.random.Generator.from_seed(42)
ran2 = ran2.normal(shape=(2,2))
ran2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [33]:
ran1 == ran2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [34]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4698825 , -0.45395887],
       [-0.7412708 , -0.09202912]], dtype=float32)>

In [35]:
co1 = tf.constant([[10,2],[30,4],[33,4],[50,5]])
co1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  2],
       [30,  4],
       [33,  4],
       [50,  5]], dtype=int32)>

In [36]:
co2 = tf.random.shuffle(co1)
co2

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[50,  5],
       [10,  2],
       [30,  4],
       [33,  4]], dtype=int32)>

In [37]:
co3 = tf.random.shuffle(co1)
co3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[33,  4],
       [10,  2],
       [50,  5],
       [30,  4]], dtype=int32)>

In [38]:
tf.random.set_seed(42)
co4 = tf.random.shuffle(co1)
co4

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[50,  5],
       [10,  2],
       [30,  4],
       [33,  4]], dtype=int32)>

In [39]:
tf.random.set_seed(42)
co5 = tf.random.shuffle(co1)
co5

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[50,  5],
       [10,  2],
       [30,  4],
       [33,  4]], dtype=int32)>

# Others

In [40]:
tf.ones([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [41]:
tf.zeros([2,2],dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

In [42]:
import numpy as np
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [43]:
tf.constant(a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [44]:
tf.constant(a,shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [45]:
b = np.arange(1,9)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
try:
  tf.constant(b,shape=(2,2))
except:
  print("Unmatched shape of transformation matrices")
  print(2*2,"doesn't equal to",8)

Unmatched shape of transformation matrices
4 doesn't equal to 8
